### ISSUE TITLE
XVFB fails to start in singularity under unknown conditions

### ISSUE THREAD

**Issue by JonahDW** [ratt-ru/Stimela#527] opened 2020-03-06 12:48 UTC
I'm going through the 'Basic MeerKAT reduction of the DEEP2 field', and everything has been working fine until inspecting the data with plotms. Following the guide and inserting 

```
recipe.add("cab/casa_plotms", "plot_ampfreq_prior", {
    "vis": "1491291289.1ghz.1.1ghz.4hrs.ms",
    "plotfile": "amp_freq_prior_rf_flag",
    "exprange": "all",
    "expformat": "png",
    "showgui": False,
    "xaxis": "frequency",
    "yaxis": "amplitude",
    "ydatacolumn": "data",
    "selectdata": True,
    "correlation": "XX,YY",
    "iteraxis": "corr",
    "coloraxis": "field",
    "showmajorgrid": True,
    "showminorgrid": False,
    "overwrite": True,
}, input=INPUT, output=OUTPUT, label="plot raw ampfreq before flagging")
```

Produces the following error:
```
2020-03-06 13:17:03,132 plot_ampfreq_prior      - casa.qtapp: cannot connect to X server :99
2020-03-06 13:17:03,132 plot_ampfreq_prior      - Traceback (most recent call last):
2020-03-06 13:17:03,133 plot_ampfreq_prior      -   File "/scratch/code/run.py", line 28, in <module>
2020-03-06 13:17:03,133 plot_ampfreq_prior      -     task.run()
2020-03-06 13:17:03,133 plot_ampfreq_prior      -   File "/usr/local/lib/python2.7/dist-packages/Crasa/Crasa.py", line 105, in run
2020-03-06 13:17:03,133 plot_ampfreq_prior      -     "-c", tfile.name])
2020-03-06 13:17:03,133 plot_ampfreq_prior      -   File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
2020-03-06 13:17:03,133 plot_ampfreq_prior      -     raise CalledProcessError(retcode, cmd)
2020-03-06 13:17:03,133 plot_ampfreq_prior      - subprocess.CalledProcessError: Command '['casa', '--nogui', '--agg', '--nocrashreport', '--log2term', '--logfile', '/scratch/output/tmp/tmp0blSLl', '-c', '/scratch/output/tmp/tmpXzMiJZ.py']' returned non-zero exit status 1
2020-03-06 13:17:03,380 - STIMELA - INFO - Recipe execution failed while running job plot_ampfreq_prior
INFO:STIMELA:Recipe execution failed while running job plot_ampfreq_prior
2020-03-06 13:17:03,380 - STIMELA - INFO - Completed jobs : []
INFO:STIMELA:Completed jobs : []
2020-03-06 13:17:03,380 - STIMELA - INFO - Remaining jobs : []
INFO:STIMELA:Remaining jobs : []
2020-03-06 13:17:03,380 - STIMELA - INFO - Saving pipeline information in .last_meerkat_ar1.5_deep2_reduction.json
INFO:STIMELA:Saving pipeline information in .last_meerkat_ar1.5_deep2_reduction.json
2020-03-06 13:17:03,383 plot_ampfreq_prior      - Stopping container [d2d]. The container ID is printed below.
Running: singularity instance.stop d2dStopping d2d instance of /.aux_mnt/pc002a/wagenveld/MeerKAT/Portable/stimela_casa_1.2.5.img (PID=21697)

Traceback (most recent call last):
  File "/usr/local/bin/stimela", line 14, in <module>
    main.main([a for a in sys.argv[1:]])
  File "/homes/wagenveld/.local/lib/python2.7/site-packages/stimela/main.py", line 640, in main
    _cmd(argv)
  File "/homes/wagenveld/.local/lib/python2.7/site-packages/stimela/main.py", line 262, in run
    exec(stdr.read(), _globals)
  File "<string>", line 72, in <module>
  File "/homes/wagenveld/.local/lib/python2.7/site-packages/stimela/recipe.py", line 1098, in run
    raise_(pe, None, sys.exc_info()[2])
  File "/homes/wagenveld/.local/lib/python2.7/site-packages/stimela/recipe.py", line 1070, in run
    run_job()
  File "/homes/wagenveld/.local/lib/python2.7/site-packages/stimela/recipe.py", line 150, in run_singularity_job
    self.job.run()
  File "/homes/wagenveld/.local/lib/python2.7/site-packages/stimela/singularity.py", line 107, in run
    timeout=self.time_out, kill_callback=self.stop)
  File "/homes/wagenveld/.local/lib/python2.7/site-packages/stimela/utils/__init__.py", line 181, in xrun
    '%s: returns errr code %d' % (command, process.returncode))
stimela.exceptions.PipelineException: Exception occurred while running pipeline component 'plot raw ampfreq before flagging': singularity run: returns errr code 1
```

I'm using singularity here. I'm not the well-versed in singularity /stimela, so the error codes don't really mean that much to me. I've already updated stimela to latest/re-pulled all the images, which does not fix the issue.

Thanks in advance.

**Comment by bennahugo** [comment] 2020-03-06 13:18
I believe this is already fixed in master. Are you using the outdated pypi version?

**Comment by JonahDW** [comment] 2020-03-06 13:29
As far as I'm aware I'm using master. I installed stimela using 

`pip install --user git+https://github.com/ratt-ru/Stimela.git`

**Comment by bennahugo** [comment] 2020-03-09 09:00
ok thanks I will look into it as soon as possible. the problem was constrained to singularity as far as I know, so for now use python2.7 and udocker if you can't use docker.

**Comment by bennahugo** [comment] 2020-03-09 12:08
I've tried to reproduce this on an X11-less machine here after pulling the latest master and image indicated in the parameter.json file (```stimela pull --force -s -im stimela/casa:1.2.5```). XVFB successfully starts:
```
INFO:root:Parameters validated and saved. Parameter file is: stimela_parameter_files/plot_afreq_bpcal_prelim-140207678931944158375462477.json
2020-03-09 13:50:30,063 plot_afreq_bpcal_prelim         - Instantiating container [6d7]. Timeout set to -1. The container ID is printed below.
Running: singularity instance.start  --bind /home/hugo/CLUSTER_SURVEY/A1300/stimela/stimela:/scratch/stimela:ro --bind /home/hugo/CLUSTER_SURVEY/A1300/stimela_parameter_files/plot_afreq_bpcal_prelim-140207678931944158375462477.json:/scratch/configfile:ro --bind /home/hugo/CLUSTER_SURVEY/A1300/stimela/stimela/cargo/cab/casa_plotms/src:/scratch/code:ro --bind /home/hugo/CLUSTER_SURVEY/A1300/stimela/stimela/cargo/cab/singularity_run:/singularity:rw --bind /home/hugo/CLUSTER_SURVEY/A1300/msdir:/scratch/msdir:rw --bind /home/hugo/CLUSTER_SURVEY/A1300/input:/scratch/input:ro --bind /home/hugo/CLUSTER_SURVEY/A1300/output/.currentjob.log:/scratch/logfile:rw --bind /home/hugo/CLUSTER_SURVEY/A1300/output:/scratch/output:rw --bind /home/hugo/CLUSTER_SURVEY/A1300/output/tmp:/scratch/output/tmp:rw -c /home/hugo/.stimela_images/stimela_casa_1.2.5.img 6d72020-03-09 13:50:32,074 plot_afreq_bpcal_prelim  - Starting container [6d7]. Timeout set to -1. The container ID is printed below.
2020-03-09 13:50:32,075 plot_afreq_bpcal_prelim         - Running: singularity run instance://6d7 
 
Starting virtual X frame buffer: Xvfb.
2020-03-09 13:50:32,585 plot_afreq_bpcal_prelim         - ZA.UTF-8"
2020-03-09 13:50:32,585 plot_afreq_bpcal_prelim         -     are supported and installed on your system.
2020-03-09 13:50:32,585 plot_afreq_bpcal_prelim         - perl: warning: Falling back to the standard locale ("C").
2020-03-09 13:50:32,686 plot_afreq_bpcal_prelim         - =========================================
2020-03-09 13:50:32,686 plot_afreq_bpcal_prelim         - The start-up time of CASA may vary
2020-03-09 13:50:32,687 plot_afreq_bpcal_prelim         - depending on whether the shared libraries
2020-03-09 13:50:32,687 plot_afreq_bpcal_prelim         - are cached or not.
2020-03-09 13:50:32,687 plot_afreq_bpcal_prelim         - =========================================
....
2020-03-09 13:55:04,432 plot_afreq_bpcal_prelim         - 2020-03-09 11:55:04   INFO    plotms::::      Plot file /scratch/output/A1300.prelim.bp.ampfreq.png
2020-03-09 13:55:04,934 plot_afreq_bpcal_prelim         - 2020-03-09 11:55:05   INFO    plotms::::      Exporting the plot.
2020-03-09 13:55:15,462 plot_afreq_bpcal_prelim         - 2020-03-09 11:55:15   INFO    plotms::::      ##### End Task: plotms               #####
2020-03-09 13:55:15,462 plot_afreq_bpcal_prelim         - 2020-03-09 11:55:15   INFO    plotms::::+     ##########################################
```

It doesn't stop xvfb successfully though, so there is a bug in the singularity runner, but I can't reproduce the failure of activating a virtual X11 server on port 99. Waiting on @SpheMakh to send me his failure mode.

**Comment by bennahugo** [comment] 2020-03-09 12:14
Running singularity version 2.6.0-dist this side.

**Comment by SpheMakh** [comment] 2020-03-09 12:33
First, a couple of syntax errors:
These 
```
    "xaxis": "frequency",
    "yaxis": "amplitude",
```
should be

```
"xaxis" : "freq",
"yaxis" : "amp",
```

**Comment by SpheMakh** [comment] 2020-03-09 12:34
For me, xvfb starts but then plotms fails at the end with a  `casa.qtapp: cannot connect to X server :99` error

```
--> CrashReporter initialized.
2020-03-09 12:29:12	INFO	plotms::::	
2020-03-09 12:29:12	INFO	plotms::::+	##########################################
2020-03-09 12:29:12	INFO	plotms::::+	##### Begin Task: plotms             #####
2020-03-09 12:29:12	INFO	plotms::::	plotms(vis="/scratch/msdir/singularity_test.ms",gridrows=1,gridcols=1,rowindex=0,colindex=0,
2020-03-09 12:29:12	INFO	plotms::::+	        plotindex=0,xaxis="freq",xdatacolumn="",xframe="",xinterp="",
2020-03-09 12:29:12	INFO	plotms::::+	        yaxis="amp",ydatacolumn="data",yframe="",yinterp="",yaxislocation="",
2020-03-09 12:29:12	INFO	plotms::::+	        selectdata=True,field="",spw="",timerange="",uvrange="",
2020-03-09 12:29:12	INFO	plotms::::+	        antenna="",scan="",correlation="XX,YY",array="",observation="",
2020-03-09 12:29:12	INFO	plotms::::+	        intent="",feed="",msselect="",averagedata=True,avgchannel="",
2020-03-09 12:29:12	INFO	plotms::::+	        avgtime="",avgscan=False,avgfield=False,avgbaseline=False,avgantenna=False,
2020-03-09 12:29:12	INFO	plotms::::+	        avgspw=False,scalar=False,transform=True,freqframe="",restfreq="",
2020-03-09 12:29:12	INFO	plotms::::+	        veldef="RADIO",shift=[0.0, 0.0],extendflag=False,extcorr=False,extchannel=False,
2020-03-09 12:29:12	INFO	plotms::::+	        iteraxis="corr",xselfscale=False,yselfscale=False,xsharedaxis=False,ysharedaxis=False,
2020-03-09 12:29:12	INFO	plotms::::+	        customsymbol=False,symbolshape="autoscaling",symbolsize=2,symbolcolor="0000ff",symbolfill="fill",
2020-03-09 12:29:12	INFO	plotms::::+	        symboloutline=False,coloraxis="field",customflaggedsymbol=False,flaggedsymbolshape="nosymbol",flaggedsymbolsize=2,
2020-03-09 12:29:12	INFO	plotms::::+	        flaggedsymbolcolor="ff0000",flaggedsymbolfill="fill",flaggedsymboloutline=False,xconnector="",timeconnector=False,
2020-03-09 12:29:12	INFO	plotms::::+	        plotrange=[],title="",titlefont=0,xlabel="",xaxisfont=0,
2020-03-09 12:29:12	INFO	plotms::::+	        ylabel="",yaxisfont=0,showmajorgrid=True,majorwidth=0,majorstyle="",
2020-03-09 12:29:12	INFO	plotms::::+	        majorcolor="B0B0B0",showminorgrid=False,minorwidth=0,minorstyle="",minorcolor="D0D0D0",
2020-03-09 12:29:12	INFO	plotms::::+	        showlegend=False,legendposition="",plotfile="/scratch/output/amp_freq_prior_rf_flag.png",expformat="png",verbose=True,
2020-03-09 12:29:12	INFO	plotms::::+	        exprange="all",highres=False,dpi=-1,width=-1,height=-1,
2020-03-09 12:29:12	INFO	plotms::::+	        overwrite=True,showgui=False,clearplots=True,callib=[''],headeritems="",
2020-03-09 12:29:12	INFO	plotms::::+	        showatm=False,showtsky=False,showimage=False)
casa.qtapp: cannot connect to X server :99
Traceback (most recent call last):
  File "/scratch/code/run.py", line 28, in <module>
    task.run()
  File "/usr/local/lib/python2.7/dist-packages/Crasa/Crasa.py", line 105, in run
    "-c", tfile.name])
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['casa', '--nogui', '--agg', '--nocrashreport', '--log2term', '--logfile', '/scratch/output/tmp/tmp7Mphey', '-c', '/scratch/output/tmp/tmpxFMepH.py']' returned non-zero exit status 1
```

**Comment by bennahugo** [comment] 2020-03-09 12:36
That is 

> First, a couple of syntax errors:
> These
> 
> ```
>     "xaxis": "frequency",
>     "yaxis": "amplitude",
> ```
> 
> should be
> 
> ```
> "xaxis" : "freq",
> "yaxis" : "amp",
> ```

These are accepted parameters by plotms (https://casa.nrao.edu/docs/TaskRef/plotms-task.html)

**Comment by bennahugo** [comment] 2020-03-09 12:36
Ok that is odd it means xvfb hasn't started successfully

**Comment by SpheMakh** [comment] 2020-03-09 12:42
> These are accepted parameters by plotms (https://casa.nrao.edu/docs/TaskRef/plotms-task.html)

Ahh, NVM

**Comment by JonahDW** [comment] 2020-03-09 12:46
> Running singularity version 2.6.0-dist this side.

I'm running is 2.6.1-dist

**Comment by SpheMakh** [comment] 2020-03-09 13:11
@JonahDW can you try podman? It's more stable compared singularity and doesn't require sudo to run

**Comment by bennahugo** [comment] 2020-03-20 08:32
I think I have stumbled upon a solution for this problem. It is because singularity do not give permission to users to write to /var/run inside the container that some of the other technologies do. Additional lines need to be added to the run string in the shell command, as per
https://serverfault.com/questions/159334/what-permission-to-write-pid-file-in-var-run

However, it appears to be configuration dependent @JonahDW @gigjozsa @SpheMakh , so it works on some singularity installs and not others. I think the correct work around for this is not to use the daemon to start the frame buffer and insert the shell string to background xvfb and initiate the call to the software inside the shell script.

This is very essential to have so I will first fix this ticket.

**Comment by bennahugo** [comment] 2020-04-14 13:43
@o-smirnov is this fixed with xvfb run or is it still a problem?
I've traced it down to the arguments that go into xvfb (ie usage of /var for a process id and not the init.d script that was previously used). Can you confirm?

**Comment by o-smirnov** [comment] 2020-04-14 14:29
As far as I know, no problems after we switched to ``xvfb-run -a``. The ``-a`` being crucial.

Heavy testing happening this week anyway, so I guess we'll know soon.

**Comment by SpheMakh** [comment] 2020-05-06 17:21
This should be fixed, please re-open if not.

**Closed by SpheMakh** 2020-05-06 17:21 UTC
